### PR TITLE
Change function to es6 syntax

### PR DESCRIPTION
**Pull request by roderickhsiao**
@hankhsiao @kaesonho 

minor change

### CODE REVIEW

**Comment by hankhsiao** [comment]
👍

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kaesonho** [comment]
👍

**Pull request merged**
