### PR TITLE
Add `releasedClass` prop

### PR DESCRIPTION
**Pull request by nason**
Thanks for this component. Its super handy!

We ran into a use case where we needed to apply a class to the outer container conditionally when the component was in a released state.

We're using this fork for now, but I'd love to get this merged upstream if it might help anyone else out.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by hankhsiao** [comment]
:+1: looks good to me.

**Comment by redonkulus** [comment]
Thanks @nason, released in version 1.2.0

**Pull request merged**
