### PR TITLE
update dimension when props being received

### PR DESCRIPTION
**Pull request by hankhsiao**
@kaesonho, before every update, dimensions need to be updated.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by MattHo** [comment]
:+1:

**Comment by kaesonho** [comment]
:+1:

**Pull request merged**
