### PR TITLE
support react16

### PR DESCRIPTION
**Pull request by brucewpaul**
this pr resolves https://github.com/yahoo/react-stickynode/issues/83

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
@brucewpaul thanks for helping out. Did you sign the CLA?

Also can you following update the devDeps to `^16.0.0:

```
"react": "^16.0.0",
"react-addons-test-utils": "^16.0.0",
"react-dom": "^16.0.0",
```

**Comment by brucewpaul** [comment]
@redonkulus Yup, I signed it and just updated the devdeps

**Comment by brucewpaul** [comment]
looks like there is other stuff going on. I don't have anymore time today, but will continue next week

**Comment by redonkulus** [comment]
@brucewpaul ya looks like the dependency on react-test-utils needs to change to `react-dom/test-utils`.

```
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
No coverage information was collected, exit without writing coverage information
module.js:471
    throw err;
    ^
Error: Cannot find module 'react-dom/lib/ReactTestUtils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
```

Not sure why node 7 is breaking at install time. I will just skip that version and try node 8 in the travis.yaml file.

**Comment by brucewpaul** [comment]
I'm trying to `npm install` on a clean fork and it seems like webpack is an unmet peer dep

```
├── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta
├── UNMET PEER DEPENDENCY webpack-dev-server@1.x
```

**Comment by brucewpaul** [comment]
but that should be installed with installing `grunt-webpack` but seems to be erroring with npm3.10.10

**Comment by redonkulus** [comment]
Ok you can probably add both webpack dependencies to devDeps to fix that warning.

**Comment by brucewpaul** [comment]
@redonkulus ptal, finally got it passing everything. Note the additional `tests/helpers/rAF.js` file. With updating to react16, it needs that polyfill for tests

**Comment by redonkulus** [comment]
Thanks!

**Comment by redonkulus** [comment]
@brucewpaul v1.4.0 now released. Thanks for helping out.

**Pull request merged**
