### PR TITLE
Allow sticking to bottom of container instead of top

### PR DESCRIPTION
**Pull request by bherila**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by bherila** [comment]
I signed the CLA. Not sure why the Travis build failed though :\

**Comment by redonkulus** [comment]
@hankhsiao @src-code thoughts?

**Comment by dpehrson** [comment]
I just wanted to drop a note saying that I just installed this lib in order to replace all my custom CSS, but one of the main things I need is support for the Floating-Action-Button style layout from Material Design which I think would necessitate this pull request.

I essentially need to keep a button in the bottom-right corner of a container that has a bottom-padding equal to the height of the button. The button would never be able to escape it's parent (top or bottom)

**Comment by bherila** [comment]
@redonkulus Any ETA for getting this merged and an updated package released? I may have to create my own separate npm package in the interim.

**Comment by bherila** [comment]
@dpehrson I have published a new npm package here, feel free to use it. 

https://www.npmjs.com/package/uc-react-stickynode

**Comment by bherila** [comment]
It is working at https://www.undergroundcellar.com/ (the floating email address thingy that pops up when you scroll down)

I am not sure about what's needed in the tests, maybe someone can help with that?

**Comment by BigPrimeNumbers** [comment]
Is this dead? This behavior would be helpful if supported.

**Comment by bherila** [comment]
@BigPrimeNumbers you can use https://www.npmjs.com/package/uc-react-stickynode

**Comment by bherila** [comment]
@redonkulus I don't work at this company anymore but if you want to adopt the behavior the PR is still open 💘

**Pull request closed without merging**
