### PR TITLE
import like ES6 module

### PR DESCRIPTION
**Pull request by SmirnovW**
Added a short note which described that we also can use the ES6 import style.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
@SmirnovW Want to just change the existing `require` to the es modules syntax?

**Comment by SmirnovW** [comment]
@redonkulus I just want to add this information, to be other developers would know it :)

**Comment by redonkulus** [comment]
@SmirnovW Thats fine, I'm saying we don't need to show the `require` syntax anymore. Just use the es module code.

**Comment by SmirnovW** [comment]
@redonkulus oh, I got it, so I will change my PR :)

**Pull request merged**
