### PR TITLE
Fixed typo in readme to read more naturally

### PR DESCRIPTION
**Pull request by scottwarren**
Hopefully I understand the context so that this change makes sense 🤞🏼

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by scottwarren** [comment]
I've now signed the CLA, not sure how to re-trigger the CLA check other than commit again D:

**Comment by scottwarren** [comment]
CLA check is all done now :-)

**Comment by redonkulus** [comment]
@scottwarren The diff is hard to understand what changed, what am I missing?

**Comment by scottwarren** [comment]
`In other words, it looks like the bottom of viewport pull the bottom of a sticky target down when scrolling page down` => `In other words, it looks like the bottom of viewport pulls the bottom of a sticky target down when scrolling page down`, missing `s` on the word `pull`

**Comment by redonkulus** [comment]
Ok thanks Merged!

**Pull request merged**
