### PR TITLE
Call `update()` with new state from `componentWillReceiveProps()` (Rewrite)

### PR DESCRIPTION
**Pull request by aclimatt**
Hi,

Here's the rewrite of PR #70 taking into account your feedback. We have it on a new branch because we also needed to fast-forward `master`, but don't seem to be able to change the branches in an existing MR.

### CODE REVIEW

**Comment by rikkit** [comment]
> but don't seem to be able to change the branches in an existing MR.

You could change the commit the old branch label pointed to, then force pushed - that is the way to change what's in a PR on GitHub. One way of doing such (if you need changes from master) is to either merge from master into your branch, or rebase (cleaner history) 👍

**Comment by aclimatt** [comment]
Hi, do you know why the build would be failing on `npm install`? I'm also getting the same build error with node 7.4.0 with `contextify`, and we haven't changed anything in `package.json`. Are other builds passing?

**Comment by markwoon** [comment]
@src-code Could you provide some feedback on this?  I've made the change you requested from #70.

**Comment by markwoon** [comment]
@src-code Any chance you've got a moment to provide feedback on this?  Would still like to get this merged if possible.

This PR is a update on #70 with the changes you requested.

**Comment by src-code** [comment]
@markwoon Sorry I never got around to looking at this. To be honest, I'm not eager to merge any feature changes to react-stickynode because I'm not doing any React lately, and stickynode has a bad tendency to be very brittle and break in unexpected, sometimes subtle ways.  And since this PR still doesn't include any tests doesn't help build confidence, either. 

It might make more sense to fork this project so others can maintain it, and sunset this repo, since there doesn't seem to be anyone inside Yahoo/Oath that wants to own it anymore.

**Pull request closed without merging**
