### PR TITLE
Moving to support React async mode: remove unsafe componentWillReceiveProps

### PR DESCRIPTION
**Pull request by aakula-edmunds**
Moving to support React async mode: get rid of unsafe componentWillReceiveProps

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by zetoke** [comment]
@aakula-edmunds @redonkulus  any news about this one?

**Comment by michaelDpierce** [comment]
Would love to see this one!

**Comment by anicarrr** [comment]
Merge this please!

**Comment by tkirda** [comment]
@redonkulus Can this be merged or any alternative solution provided?

**Comment by redonkulus** [comment]
Does this warrant a major upgrade to prevent existing sites from breaking?

**Comment by fitzsimonsdevin** [comment]
Seems like a reasonable approach.

**Comment by redonkulus** [comment]
Thanks everyone, this is released in v3.0.0

**Pull request merged**
